# SPDX-License-Identifier: MIT
---

- name: Configure .wslconfig
  become: true
  ansible.builtin.template:
    src: .wslconfig.j2
    dest: "{{ wslconfig_path }}"
    owner: "{{ wslconfig_owner }}"
    group: "{{ wslconfig_group }}"
    mode: "0644"
